### ISSUE TITLE
Unable to build with dynamic import

### ISSUE THREAD

**Issue by lowi** [svelte-view-engine/svelte-view-engine#2]
I tried with sve-app to use dynamic import such as:
```
<script>
let Nav;
onMount(_ => {
	import("../components/Nav.svelte").then(res => Nav = res.default);
});
</script>

{#if Nav}
<svelte:component this="{Nav}" />
{/if}
```
but I am unable to get a working build, and get this error: `Error: UMD and IIFE output formats are not supported for code-splitting builds.`

I tried with `transpile:true` and changing the format to "esm", but it's not working.

**Comment by lowi** [comment]
After investigation, I am able to make it work by doing the following changes:
1. Change buildDomComponent to generate "es" format instead of "iife" or "cjs"
2. Use `bundle.write` after `bundle.generate` to let rollup write all the generated files
    It seems there is a shortcut using `output[0]` that ignores additional files necessary for dynamic import
3. template.html should use `script type=module` to import the generated ES module

**Comment by user896724** [comment]
Thanks for this.  I'm just finishing a refactor that brings the build script into the project to avoid having it in the app, and some other clean ups, so I'll incorporate this into the release.

**Comment by lowi** [comment]
I'll share my changes in a pull request.
I am currently using sapper for a couple of websites, but I hope to replace it with svelte-view-engine (too much magic in sapper, customization is not simple, and not much reactivity on merging pull requests). 
Looking forward to next release!

**Comment by user896724** [comment]
Great!  I thought I had it working before with your changes but can't seem to get it to work now, getting "ReferenceError: Index is undefined" in the chrome console for Index.html.  It's importing it correctly but the global Index isn't defined - I'm not sure how ES modules work in the browser but I'm assuming this is because global variables in ES modules don't just get added to `window` like they would with non-module scripts?

**Comment by user896724** [comment]
(This can be seen with the latest sve-app if you add the new `dynamicImports: true` option to the svelte-view-engine config and set type=module in template.html)

**Comment by lowi** [comment]
I created the pull review to outline my changes @user896724 
https://github.com/svelte-view-engine/sve-app/pull/4

**Comment by user896724** [comment]
Hi @koudonojinchuu , thanks for the info.  I'm not actively working on svelte-view-engine at the moment but am open to PRs if you find a fix.
