### ISSUE TITLE
Bug: Could not resolve entry module

### ISSUE THREAD

**Issue by markoboy** [svelte-view-engine/svelte-view-engine#3]
Hello, I found this repo after some search and it is something that I was looking for and thanks for building this.

I'm trying to run the view engine using the example from the docs (svelte-view-engine/sve-app) but the build script fails to build the path properly.

![image](https://user-images.githubusercontent.com/35178536/97095634-e54f1e00-1659-11eb-9431-bbe7e92ae250.png)

As you can see from the image the page path is prepended in the path as well as an extra .html is added to the files extension.

The issue occurs from the Engine.js render function:

```javascript
		if (path[0] !== "/") {
			path = this.dir + "/" + path + "." + this.type;
		}
```

As this is a windows enviroment the path starts with the drive and not with a leading slash...

Maybe converting this to something like:

```javascript
		if (!path.startsWith(this.dir) && path[0] !== '/') {
			path = this.dir + "/" + path + "." + this.type;
		}
```

Would make it more reliable. I can make a pull request if you want.

Enviroment:
Windows 10 pro,
Node v13

**Comment by user896724** [comment]
Hi, thanks.  Have updated it to use `path.isAbsolute`.  Please let me know if there are any other issues.

**Comment by markoboy** [comment]
Hi, thank you, that works fine now.
